-- Generic scheduled task definitions, execution facts, and segmented logs.
-- The task service owns execution; the HTTP service only manages definitions and runs.

CREATE TABLE IF NOT EXISTS `scheduled_tasks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Task ID',
  `code` VARCHAR(100) NOT NULL COMMENT 'Stable task code',
  `name` VARCHAR(200) NOT NULL COMMENT 'Task name',
  `description` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Task description',
  `handler_type` VARCHAR(24) NOT NULL COMMENT 'Handler type',
  `handler_config_json` MEDIUMTEXT NOT NULL COMMENT 'Handler configuration JSON',
  `cron_expression` VARCHAR(120) NOT NULL COMMENT 'Cron expression',
  `cron_precision` VARCHAR(16) NOT NULL DEFAULT 'minute' COMMENT 'minute or second',
  `timezone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT 'IANA timezone',
  `enabled` TINYINT NOT NULL DEFAULT 0 COMMENT 'Whether scheduling is enabled',
  `misfire_policy` VARCHAR(24) NOT NULL DEFAULT 'skip' COMMENT 'Misfire policy',
  `max_catch_up` INT NOT NULL DEFAULT 1 COMMENT 'Maximum catch-up runs',
  `concurrency_policy` VARCHAR(24) NOT NULL DEFAULT 'skip' COMMENT 'Concurrency policy',
  `timeout_seconds` INT NOT NULL DEFAULT 300 COMMENT 'Execution timeout seconds',
  `max_retries` INT NOT NULL DEFAULT 0 COMMENT 'Maximum automatic retries',
  `retry_backoff_json` MEDIUMTEXT NOT NULL COMMENT 'Retry backoff configuration JSON',
  `last_scheduled_at` BIGINT NOT NULL DEFAULT 0 COMMENT 'Last processed schedule in UTC milliseconds',
  `next_run_at` BIGINT NOT NULL DEFAULT 0 COMMENT 'Next schedule in UTC milliseconds',
  `version` BIGINT NOT NULL DEFAULT 1 COMMENT 'Optimistic lock version',
  `created_by` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Creator admin user ID',
  `updated_by` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Updater admin user ID',
  `deleted_at` BIGINT NOT NULL DEFAULT 0 COMMENT 'Soft deletion time in milliseconds',
  `add_time` BIGINT NOT NULL DEFAULT 0 COMMENT 'Creation time in milliseconds',
  `edit_time` BIGINT NOT NULL DEFAULT 0 COMMENT 'Update time in milliseconds',
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scheduled_task_code` (`code`),
  KEY `idx_scheduled_tasks_due` (`enabled`,`next_run_at`),
  KEY `idx_scheduled_tasks_handler` (`handler_type`,`enabled`),
  KEY `idx_scheduled_tasks_deleted` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Generic scheduled task definitions';

CREATE TABLE IF NOT EXISTS `scheduled_task_runs` (
  `id` VARCHAR(64) NOT NULL COMMENT 'Run ID',
  `run_key` VARCHAR(191) NOT NULL COMMENT 'Globally unique idempotency key',
  `task_id` BIGINT UNSIGNED NOT NULL COMMENT 'Task ID',
  `parent_run_id` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Manual retry source run ID',
  `trigger_type` VARCHAR(24) NOT NULL COMMENT 'Trigger type',
  `run_status` VARCHAR(24) NOT NULL DEFAULT 'queued' COMMENT 'Run status',
  `task_snapshot_json` MEDIUMTEXT NOT NULL COMMENT 'Immutable task snapshot JSON',
  `scheduled_at` BIGINT NOT NULL DEFAULT 0 COMMENT 'Scheduled UTC time in milliseconds',
  `coalesced_count` INT NOT NULL DEFAULT 1 COMMENT 'Number of coalesced triggers',
  `attempt` INT NOT NULL DEFAULT 0 COMMENT 'Current automatic attempt',
  `worker_id` VARCHAR(160) NOT NULL DEFAULT '' COMMENT 'Worker that owns the run',
  `redis_message_id` VARCHAR(80) NOT NULL DEFAULT '' COMMENT 'Latest Redis Stream message ID',
  `queued_at` BIGINT NOT NULL DEFAULT 0 COMMENT 'Queue time in milliseconds',
  `started_at` BIGINT NOT NULL DEFAULT 0 COMMENT 'Start time in milliseconds',
  `finished_at` BIGINT NOT NULL DEFAULT 0 COMMENT 'Finish time in milliseconds',
  `heartbeat_at` BIGINT NOT NULL DEFAULT 0 COMMENT 'Worker heartbeat in milliseconds',
  `next_retry_at` BIGINT NOT NULL DEFAULT 0 COMMENT 'Next retry time in milliseconds',
  `cancel_requested_at` BIGINT NOT NULL DEFAULT 0 COMMENT 'Cancellation request time in milliseconds',
  `result_summary` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT 'Redacted result summary',
  `error_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Classified error code',
  `error_summary` VARCHAR(2000) NOT NULL DEFAULT '' COMMENT 'Redacted error summary',
  `add_time` BIGINT NOT NULL DEFAULT 0 COMMENT 'Creation time in milliseconds',
  `edit_time` BIGINT NOT NULL DEFAULT 0 COMMENT 'Update time in milliseconds',
  `created_at` DATETIME(3) DEFAULT NULL,
  `updated_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scheduled_task_run_key` (`run_key`),
  KEY `idx_scheduled_task_runs_task_time` (`task_id`,`scheduled_at`),
  KEY `idx_scheduled_task_runs_due` (`run_status`,`next_retry_at`),
  KEY `idx_scheduled_task_runs_recovery` (`run_status`,`heartbeat_at`),
  KEY `idx_scheduled_task_runs_parent` (`parent_run_id`),
  CONSTRAINT `fk_scheduled_task_runs_task` FOREIGN KEY (`task_id`) REFERENCES `scheduled_tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Generic scheduled task execution facts';

CREATE TABLE IF NOT EXISTS `scheduled_task_run_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Log segment ID',
  `run_id` VARCHAR(64) NOT NULL COMMENT 'Run ID',
  `log_sequence` INT NOT NULL COMMENT 'Sequence within the run',
  `log_level` VARCHAR(16) NOT NULL DEFAULT 'info' COMMENT 'Log level',
  `log_stage` VARCHAR(40) NOT NULL DEFAULT '' COMMENT 'Execution stage',
  `log_content` MEDIUMTEXT NOT NULL COMMENT 'Redacted log content',
  `log_time` BIGINT NOT NULL DEFAULT 0 COMMENT 'Log time in milliseconds',
  `add_time` BIGINT NOT NULL DEFAULT 0 COMMENT 'Creation time in milliseconds',
  `created_at` DATETIME(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_scheduled_task_run_logs_run_seq` (`run_id`,`log_sequence`),
  CONSTRAINT `fk_scheduled_task_run_logs_run` FOREIGN KEY (`run_id`) REFERENCES `scheduled_task_runs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Scheduled task segmented execution logs';
