-- 为已完成权限初始化的数据库补齐通用工作流运行时权限。
-- 本迁移只注册权限定义，不自动给普通角色授权。

INSERT INTO `permissions` (
  `permission_key`, `permission_name`, `permission_platform`, `permission_type`,
  `permission_parent_key`, `permission_resource_path`, `permission_icon`, `permission_perms`,
  `permission_sort`, `permission_status`, `permission_add_time`, `permission_edit_time`,
  `created_at`, `updated_at`
) VALUES
  ('admin:menu:workflow:instances', '流程实例', 'admin', 'menu',
   'admin:menu:workflow', '/workflow/instances', '', 'workflow:instance:list',
   2, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:workflow:tasks', '流程任务', 'admin', 'menu',
   'admin:menu:workflow', '/workflow/tasks', '', 'workflow:task:list',
   3, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:workflow:instance:list', '流程实例查看', 'admin', 'button',
   'admin:menu:workflow:instances', '', '', 'workflow:instance:list',
   1, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:workflow:instance:start', '发起流程实例', 'admin', 'button',
   'admin:menu:workflow:instances', '', '', 'workflow:instance:start',
   2, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:workflow:instance:detail', '流程实例详情', 'admin', 'button',
   'admin:menu:workflow:instances', '', '', 'workflow:instance:detail',
   3, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:workflow:task:list', '流程任务查看', 'admin', 'button',
   'admin:menu:workflow:tasks', '', '', 'workflow:task:list',
   1, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:workflow:task:complete', '处理流程任务', 'admin', 'button',
   'admin:menu:workflow:tasks', '', '', 'workflow:task:complete',
   2, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:workflow:instance:list', '流程实例查看接口', 'admin', 'api',
   'admin:api-category:workflow', '/api/v2/admin/workflow-instances', '', 'workflow:instance:list',
   350, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:workflow:instance:start', '流程实例发起接口', 'admin', 'api',
   'admin:api-category:workflow', '/api/v2/admin/workflow-instances', '', 'workflow:instance:start',
   360, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:workflow:instance:detail', '流程实例详情接口', 'admin', 'api',
   'admin:api-category:workflow', '/api/v2/admin/workflow-instances/:id', '', 'workflow:instance:detail',
   370, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:workflow:task:list', '流程任务查看接口', 'admin', 'api',
   'admin:api-category:workflow', '/api/v2/admin/workflow-tasks', '', 'workflow:task:list',
   380, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:workflow:task:complete', '流程任务处理接口', 'admin', 'api',
   'admin:api-category:workflow', '/api/v2/admin/workflow-tasks/:id/complete', '', 'workflow:task:complete',
   390, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3))
ON DUPLICATE KEY UPDATE
  `permission_name` = VALUES(`permission_name`),
  `permission_platform` = VALUES(`permission_platform`),
  `permission_type` = VALUES(`permission_type`),
  `permission_parent_key` = VALUES(`permission_parent_key`),
  `permission_resource_path` = VALUES(`permission_resource_path`),
  `permission_icon` = VALUES(`permission_icon`),
  `permission_perms` = VALUES(`permission_perms`),
  `permission_sort` = VALUES(`permission_sort`),
  `permission_status` = 1,
  `permission_edit_time` = VALUES(`permission_edit_time`),
  `updated_at` = NOW(3);
