-- 注册通用定时任务管理权限。
-- 只补齐权限定义，不自动给普通角色授权。

INSERT INTO `permissions` (
  `permission_key`, `permission_name`, `permission_platform`, `permission_type`,
  `permission_parent_key`, `permission_resource_path`, `permission_icon`, `permission_perms`,
  `permission_sort`, `permission_status`, `permission_add_time`, `permission_edit_time`,
  `created_at`, `updated_at`
) VALUES
  ('admin:menu:scheduled-task', '定时任务', 'admin', 'directory',
   '', '/scheduled-task', 'Timer', 'scheduled-task:list',
   18, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:tasks', '任务管理', 'admin', 'menu',
   'admin:menu:scheduled-task', '/scheduled-task/tasks', '', 'scheduled-task:list',
   1, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:runs', '运行记录', 'admin', 'menu',
   'admin:menu:scheduled-task', '/scheduled-task/runs', '', 'scheduled-task:run:list',
   2, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:workers', '执行节点', 'admin', 'menu',
   'admin:menu:scheduled-task', '/scheduled-task/workers', '', 'scheduled-task:worker:list',
   3, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:list', '定时任务查看', 'admin', 'button',
   'admin:menu:scheduled-task:tasks', '', '', 'scheduled-task:list',
   1, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:add', '定时任务创建', 'admin', 'button',
   'admin:menu:scheduled-task:tasks', '', '', 'scheduled-task:add',
   2, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:edit', '定时任务编辑', 'admin', 'button',
   'admin:menu:scheduled-task:tasks', '', '', 'scheduled-task:edit',
   3, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:delete', '定时任务删除', 'admin', 'button',
   'admin:menu:scheduled-task:tasks', '', '', 'scheduled-task:delete',
   4, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:status', '定时任务启停', 'admin', 'button',
   'admin:menu:scheduled-task:tasks', '', '', 'scheduled-task:status',
   5, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:run', '立即运行', 'admin', 'button',
   'admin:menu:scheduled-task:tasks', '', '', 'scheduled-task:run',
   6, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:http', '配置 HTTP 任务', 'admin', 'button',
   'admin:menu:scheduled-task:tasks', '', '', 'scheduled-task:http',
   7, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:shell', '配置 Shell 任务', 'admin', 'button',
   'admin:menu:scheduled-task:tasks', '', '', 'scheduled-task:shell',
   8, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:sql:read', '配置 SQL 查询任务', 'admin', 'button',
   'admin:menu:scheduled-task:tasks', '', '', 'scheduled-task:sql:read',
   9, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:sql:write', '配置 SQL 写入任务', 'admin', 'button',
   'admin:menu:scheduled-task:tasks', '', '', 'scheduled-task:sql:write',
   10, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:run:list', '运行记录查看', 'admin', 'button',
   'admin:menu:scheduled-task:runs', '', '', 'scheduled-task:run:list',
   1, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:run:retry', '运行记录重试', 'admin', 'button',
   'admin:menu:scheduled-task:runs', '', '', 'scheduled-task:run:retry',
   2, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:run:cancel', '运行记录取消', 'admin', 'button',
   'admin:menu:scheduled-task:runs', '', '', 'scheduled-task:run:cancel',
   3, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:menu:scheduled-task:worker:list', '执行节点查看', 'admin', 'button',
   'admin:menu:scheduled-task:workers', '', '', 'scheduled-task:worker:list',
   1, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api-category:scheduled-task', '定时任务', 'admin', 'api_category',
   '', '', '', '',
   80, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:list', '定时任务查看接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-tasks', '', 'scheduled-task:list',
   10, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:add', '定时任务创建接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-tasks', '', 'scheduled-task:add',
   20, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:edit', '定时任务编辑接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-tasks/:id', '', 'scheduled-task:edit',
   30, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:delete', '定时任务删除接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-tasks/:id', '', 'scheduled-task:delete',
   40, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:status', '定时任务启停接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-tasks/:id/status', '', 'scheduled-task:status',
   50, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:run', '定时任务立即运行接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-tasks/:id/run', '', 'scheduled-task:run',
   60, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:run:list', '定时任务运行记录查看接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-task-runs', '', 'scheduled-task:run:list',
   70, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:run:retry', '定时任务运行重试接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-task-runs/:id/retry', '', 'scheduled-task:run:retry',
   80, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:run:cancel', '定时任务运行取消接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-task-runs/:id/cancel', '', 'scheduled-task:run:cancel',
   90, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:worker:list', '定时任务执行节点查看接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-task-workers', '', 'scheduled-task:worker:list',
   100, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:http', '定时任务 HTTP 处理器配置接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-tasks', '', 'scheduled-task:http',
   110, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:shell', '定时任务 Shell 处理器配置接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-tasks', '', 'scheduled-task:shell',
   120, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:sql:read', '定时任务 SQL 查询配置接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-tasks', '', 'scheduled-task:sql:read',
   130, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3)),
  ('admin:api:scheduled-task:sql:write', '定时任务 SQL 写入配置接口', 'admin', 'api',
   'admin:api-category:scheduled-task', '/api/v2/admin/scheduled-tasks', '', 'scheduled-task:sql:write',
   140, 1, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000, NOW(3), NOW(3))
ON DUPLICATE KEY UPDATE
  `permission_name` = VALUES(`permission_name`),
  `permission_platform` = VALUES(`permission_platform`),
  `permission_type` = VALUES(`permission_type`),
  `permission_parent_key` = VALUES(`permission_parent_key`),
  `permission_resource_path` = VALUES(`permission_resource_path`),
  `permission_icon` = VALUES(`permission_icon`),
  `permission_perms` = VALUES(`permission_perms`),
  `permission_sort` = VALUES(`permission_sort`),
  `permission_status` = 1,
  `permission_edit_time` = VALUES(`permission_edit_time`),
  `updated_at` = NOW(3);
