-- 完成流程的表单修订、确认任务和业务事件 Outbox。

CREATE TABLE IF NOT EXISTS `workflow_form_revision_requests` (
  `id` varchar(64) NOT NULL COMMENT '表单修订请求ID',
  `source_instance_id` varchar(64) NOT NULL COMMENT '原流程实例ID',
  `source_node_id` varchar(100) NOT NULL COMMENT '修订来源节点ID快照',
  `source_node_name` varchar(200) NOT NULL DEFAULT '' COMMENT '修订来源节点名称快照',
  `requester_id` varchar(64) NOT NULL COMMENT '修订发起人ID',
  `base_form_revision` bigint NOT NULL COMMENT '修订基准表单版本',
  `before_form_data_json` mediumtext NOT NULL COMMENT '修改前表单JSON快照',
  `patch_json` mediumtext NOT NULL COMMENT '修订补丁JSON',
  `proposed_form_data_json` mediumtext NOT NULL COMMENT '候选表单JSON快照',
  `changed_field_labels_json` mediumtext NOT NULL COMMENT '修改字段名称JSON快照',
  `reason` varchar(500) NOT NULL COMMENT '修订原因',
  `revision_mode` varchar(32) NOT NULL COMMENT 'direct或downstream_review',
  `revision_status` varchar(24) NOT NULL COMMENT '修订状态',
  `active_lock_key` varchar(64) DEFAULT NULL COMMENT '进行中修订唯一锁',
  `applied_form_revision` bigint NOT NULL DEFAULT 0 COMMENT '生效后的表单版本',
  `add_time` bigint NOT NULL COMMENT '创建时间',
  `edit_time` bigint NOT NULL COMMENT '更新时间',
  `completed_at` bigint NOT NULL DEFAULT 0 COMMENT '终态时间',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_workflow_form_revision_active` (`active_lock_key`),
  KEY `idx_workflow_form_revision_instance_time` (`source_instance_id`,`add_time`),
  KEY `idx_workflow_form_revision_requester_time` (`requester_id`,`add_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='完成流程表单修订请求';

CREATE TABLE IF NOT EXISTS `workflow_form_revision_tasks` (
  `id` varchar(64) NOT NULL COMMENT '表单修订任务ID',
  `revision_request_id` varchar(64) NOT NULL COMMENT '修订请求ID',
  `source_task_id` varchar(64) NOT NULL DEFAULT '' COMMENT '原流程任务ID快照',
  `node_id` varchar(100) NOT NULL COMMENT '确认节点ID快照',
  `node_name` varchar(200) NOT NULL DEFAULT '' COMMENT '确认节点名称快照',
  `stage` int NOT NULL COMMENT '确认阶段',
  `assignee_id` varchar(64) NOT NULL COMMENT '任务处理人ID',
  `assignee_name` varchar(200) NOT NULL DEFAULT '' COMMENT '任务处理人名称快照',
  `approval_mode` varchar(24) NOT NULL DEFAULT 'single' COMMENT '审批模式',
  `completion_rate` int NOT NULL DEFAULT 100 COMMENT '会签通过比例',
  `task_sequence` int NOT NULL DEFAULT 1 COMMENT '组内顺序',
  `task_total` int NOT NULL DEFAULT 1 COMMENT '组内任务总数',
  `task_status` varchar(24) NOT NULL DEFAULT 'waiting' COMMENT '任务状态',
  `task_action` varchar(24) NOT NULL DEFAULT '' COMMENT '处理动作',
  `task_comment` varchar(1000) NOT NULL DEFAULT '' COMMENT '处理意见',
  `task_images_json` mediumtext NOT NULL COMMENT '处理图片JSON',
  `handled_by` varchar(64) NOT NULL DEFAULT '' COMMENT '实际处理人ID',
  `handled_at` bigint NOT NULL DEFAULT 0 COMMENT '处理时间',
  `add_time` bigint NOT NULL COMMENT '创建时间',
  `edit_time` bigint NOT NULL COMMENT '更新时间',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_workflow_form_revision_task_assignee` (`assignee_id`,`task_status`,`add_time`),
  KEY `idx_workflow_form_revision_task_stage` (`revision_request_id`,`stage`,`task_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='完成流程表单修订确认任务';

CREATE TABLE IF NOT EXISTS `workflow_business_event_outbox` (
  `id` varchar(64) NOT NULL COMMENT '业务事件Outbox ID',
  `event_type` varchar(100) NOT NULL COMMENT '业务事件类型',
  `aggregate_id` varchar(64) NOT NULL COMMENT '聚合ID',
  `business_type` varchar(100) NOT NULL DEFAULT '' COMMENT '业务类型',
  `business_key` varchar(160) NOT NULL DEFAULT '' COMMENT '业务标识',
  `payload_json` mediumtext NOT NULL COMMENT '事件负载JSON',
  `event_status` varchar(24) NOT NULL DEFAULT 'pending' COMMENT '派发状态',
  `dedupe_key` varchar(191) NOT NULL COMMENT '事件幂等键',
  `attempts` int NOT NULL DEFAULT 0 COMMENT '派发尝试次数',
  `next_retry_at` bigint NOT NULL DEFAULT 0 COMMENT '下次重试时间',
  `last_error` varchar(1000) NOT NULL DEFAULT '' COMMENT '最近失败摘要',
  `sent_at` bigint NOT NULL DEFAULT 0 COMMENT '派发成功时间',
  `add_time` bigint NOT NULL COMMENT '创建时间',
  `edit_time` bigint NOT NULL COMMENT '更新时间',
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_workflow_business_event_dedupe` (`dedupe_key`),
  KEY `idx_workflow_business_event_due` (`event_status`,`next_retry_at`),
  KEY `idx_workflow_business_event_aggregate` (`aggregate_id`),
  KEY `idx_workflow_business_event_reference` (`business_type`,`business_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='工作流业务事件Outbox';

SET @workflow_business_event_now = CAST(UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000 AS SIGNED);

INSERT INTO `scheduled_tasks` (
  `code`, `name`, `description`, `handler_type`, `handler_config_json`,
  `cron_expression`, `cron_precision`, `timezone`, `enabled`, `misfire_policy`,
  `max_catch_up`, `concurrency_policy`, `timeout_seconds`, `max_retries`, `retry_backoff_json`,
  `last_scheduled_at`, `next_run_at`, `version`, `created_by`, `updated_by`, `deleted_at`,
  `add_time`, `edit_time`
) VALUES (
  'system.workflow-business-event-dispatch',
  '工作流业务事件派发',
  '由 taskd 派发到期的工作流业务事件 Outbox 记录',
  'go',
  '{"handlerKey":"workflow.business-event.dispatch_due","params":{"limit":100}}',
  '* * * * *',
  'minute',
  'Asia/Shanghai',
  1,
  'skip',
  1,
  'skip',
  60,
  2,
  '{"type":"fixed","seconds":30}',
  0,
  @workflow_business_event_now,
  1,
  0,
  0,
  0,
  @workflow_business_event_now,
  @workflow_business_event_now
)
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `description` = VALUES(`description`),
  `handler_type` = VALUES(`handler_type`),
  `handler_config_json` = VALUES(`handler_config_json`),
  `cron_expression` = VALUES(`cron_expression`),
  `cron_precision` = VALUES(`cron_precision`),
  `timezone` = VALUES(`timezone`),
  `enabled` = 1,
  `misfire_policy` = VALUES(`misfire_policy`),
  `max_catch_up` = VALUES(`max_catch_up`),
  `concurrency_policy` = VALUES(`concurrency_policy`),
  `timeout_seconds` = VALUES(`timeout_seconds`),
  `max_retries` = VALUES(`max_retries`),
  `retry_backoff_json` = VALUES(`retry_backoff_json`),
  `next_run_at` = IF(`next_run_at` > 0, `next_run_at`, @workflow_business_event_now),
  `deleted_at` = 0,
  `edit_time` = @workflow_business_event_now;
