// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/clear_vouch": {
            "get": {
                "tags": [
                    "管理后台首页"
                ],
                "summary": "清除推荐数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_clear": {
            "post": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "清除打卡全部数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_del": {
            "post": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "删除打卡项目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_detail": {
            "get": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "获取打卡项目详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_edit": {
            "post": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "编辑打卡项目",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_insert": {
            "post": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "新增打卡项目",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_join_data_del": {
            "post": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "删除打卡导出数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "enrollId",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_join_data_export": {
            "get": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "导出打卡数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "enrollId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_join_data_get": {
            "get": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "获取打卡数据导出链接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "enrollId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_join_del": {
            "post": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "删除打卡记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "记录ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_join_list": {
            "get": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "获取打卡记录列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "enrollId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_list": {
            "get": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "获取打卡项目列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_sort": {
            "post": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "打卡项目排序",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "排序值",
                        "name": "sort",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_status": {
            "post": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "设置打卡状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_update_forms": {
            "post": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "更新打卡表单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "表单数据",
                        "name": "forms",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/enroll_vouch": {
            "post": {
                "tags": [
                    "打卡管理"
                ],
                "summary": "设置打卡推荐",
                "parameters": [
                    {
                        "type": "string",
                        "description": "项目ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "推荐值",
                        "name": "vouch",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/home": {
            "get": {
                "tags": [
                    "管理后台首页"
                ],
                "summary": "管理后台首页数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/log_clear": {
            "get": {
                "tags": [
                    "管理员管理"
                ],
                "summary": "清除操作日志",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/log_list": {
            "get": {
                "tags": [
                    "管理员管理"
                ],
                "summary": "获取操作日志列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/login": {
            "post": {
                "tags": [
                    "管理员管理"
                ],
                "summary": "管理员登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/mgr_del": {
            "post": {
                "tags": [
                    "管理员管理"
                ],
                "summary": "删除管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "管理员ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/mgr_detail": {
            "get": {
                "tags": [
                    "管理员管理"
                ],
                "summary": "获取管理员详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "管理员ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/mgr_edit": {
            "post": {
                "tags": [
                    "管理员管理"
                ],
                "summary": "编辑管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "管理员ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "描述",
                        "name": "desc",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/mgr_insert": {
            "post": {
                "tags": [
                    "管理员管理"
                ],
                "summary": "新增管理员",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "描述",
                        "name": "desc",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "phone",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/mgr_list": {
            "get": {
                "tags": [
                    "管理员管理"
                ],
                "summary": "获取管理员列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/mgr_pwd": {
            "post": {
                "tags": [
                    "管理员管理"
                ],
                "summary": "修改管理员密码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "管理员ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/mgr_status": {
            "post": {
                "tags": [
                    "管理员管理"
                ],
                "summary": "设置管理员状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "管理员ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/news_del": {
            "post": {
                "tags": [
                    "新闻管理"
                ],
                "summary": "删除新闻",
                "parameters": [
                    {
                        "type": "string",
                        "description": "新闻ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/news_detail": {
            "get": {
                "tags": [
                    "新闻管理"
                ],
                "summary": "获取新闻详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "新闻ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/news_edit": {
            "post": {
                "tags": [
                    "新闻管理"
                ],
                "summary": "编辑新闻",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/news_insert": {
            "post": {
                "tags": [
                    "新闻管理"
                ],
                "summary": "新增新闻",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/news_list": {
            "get": {
                "tags": [
                    "新闻管理"
                ],
                "summary": "获取新闻列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/news_sort": {
            "post": {
                "tags": [
                    "新闻管理"
                ],
                "summary": "新闻排序",
                "parameters": [
                    {
                        "type": "string",
                        "description": "新闻ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "排序值",
                        "name": "sort",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/news_status": {
            "post": {
                "tags": [
                    "新闻管理"
                ],
                "summary": "设置新闻状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "新闻ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/news_update_content": {
            "post": {
                "tags": [
                    "新闻管理"
                ],
                "summary": "更新新闻内容",
                "parameters": [
                    {
                        "type": "string",
                        "description": "新闻ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "内容",
                        "name": "content",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/news_update_forms": {
            "post": {
                "tags": [
                    "新闻管理"
                ],
                "summary": "更新新闻表单",
                "parameters": [
                    {
                        "type": "string",
                        "description": "新闻ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "表单数据",
                        "name": "forms",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/news_update_pic": {
            "post": {
                "tags": [
                    "新闻管理"
                ],
                "summary": "更新新闻图片",
                "parameters": [
                    {
                        "type": "string",
                        "description": "新闻ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "图片数据",
                        "name": "pic",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/setup_qr": {
            "get": {
                "tags": [
                    "系统设置"
                ],
                "summary": "生成小程序码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "页面路径",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "场景值",
                        "name": "scene",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/setup_set": {
            "post": {
                "tags": [
                    "系统设置"
                ],
                "summary": "设置系统配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设置键名",
                        "name": "key",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "设置值",
                        "name": "value",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/setup_set_content": {
            "post": {
                "tags": [
                    "系统设置"
                ],
                "summary": "设置内容配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设置键名",
                        "name": "key",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "设置值",
                        "name": "value",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/user_data_del": {
            "post": {
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/user_data_export": {
            "get": {
                "tags": [
                    "用户管理"
                ],
                "summary": "导出用户数据",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/user_data_get": {
            "get": {
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户数据导出链接",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/user_del": {
            "post": {
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/user_detail": {
            "get": {
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户OpenID",
                        "name": "openid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/user_list": {
            "get": {
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键词",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/admin/user_status": {
            "post": {
                "tags": [
                    "用户管理"
                ],
                "summary": "设置用户状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "状态",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/enroll/join": {
            "post": {
                "tags": [
                    "报名"
                ],
                "summary": "用户报名打卡",
                "parameters": [
                    {
                        "type": "string",
                        "description": "报名ID",
                        "name": "enroll_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日期",
                        "name": "day",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "表单数据",
                        "name": "forms",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/enroll/join_day": {
            "get": {
                "tags": [
                    "报名"
                ],
                "summary": "按日获取报名打卡记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "报名ID",
                        "name": "enroll_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日期",
                        "name": "day",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/enroll/list": {
            "get": {
                "tags": [
                    "报名"
                ],
                "summary": "获取报名列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/enroll/my_join_list": {
            "get": {
                "tags": [
                    "报名"
                ],
                "summary": "获取我的打卡记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/enroll/my_user_list": {
            "get": {
                "tags": [
                    "报名"
                ],
                "summary": "获取我的报名用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/enroll/view": {
            "get": {
                "tags": [
                    "报名"
                ],
                "summary": "查看报名详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "报名ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/fav/del": {
            "post": {
                "tags": [
                    "收藏"
                ],
                "summary": "删除收藏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "对象ID",
                        "name": "oid",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/fav/is_fav": {
            "get": {
                "tags": [
                    "收藏"
                ],
                "summary": "是否已收藏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "对象ID",
                        "name": "oid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "类型",
                        "name": "typ",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/fav/my_list": {
            "get": {
                "tags": [
                    "收藏"
                ],
                "summary": "获取我的收藏列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "类型",
                        "name": "typ",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/fav/update": {
            "post": {
                "tags": [
                    "收藏"
                ],
                "summary": "更新收藏",
                "parameters": [
                    {
                        "type": "string",
                        "description": "标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "对象ID",
                        "name": "oid",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "类型",
                        "name": "typ",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "路径",
                        "name": "path",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/home/list": {
            "get": {
                "tags": [
                    "首页"
                ],
                "summary": "获取首页列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/home/setup_get": {
            "get": {
                "tags": [
                    "首页"
                ],
                "summary": "获取系统设置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设置键名",
                        "name": "key",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/news/list": {
            "get": {
                "tags": [
                    "新闻"
                ],
                "summary": "获取新闻列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/news/view": {
            "get": {
                "tags": [
                    "新闻"
                ],
                "summary": "查看新闻详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "新闻ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/passport/edit_base": {
            "post": {
                "tags": [
                    "通行证"
                ],
                "summary": "编辑基本信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "mobile",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "头像",
                        "name": "pic",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/passport/login": {
            "post": {
                "tags": [
                    "通行证"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/passport/my_detail": {
            "get": {
                "tags": [
                    "通行证"
                ],
                "summary": "获取我的详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/passport/phone": {
            "post": {
                "tags": [
                    "通行证"
                ],
                "summary": "获取手机号",
                "parameters": [
                    {
                        "type": "string",
                        "description": "云ID",
                        "name": "cloud_id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        },
        "/passport/register": {
            "post": {
                "tags": [
                    "通行证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户ID",
                        "name": "user_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "姓名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "mobile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "头像",
                        "name": "pic",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Resp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "response.Resp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "WeCheckin API",
	Description:      "微信小程序打卡项目后端 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
