export type DingTalkH5IconOption = {
  label: string
  value: string
  aliases?: string[]
}

export const DINGTALK_H5_ICON_NAMES = [
  'en',
  'zh',
  'level',
  'woman',
  'man',
  'column-line',
  'empty-page',
  'empty-data',
  'empty-car',
  'empty-order',
  'empty-address',
  'empty-message',
  'empty-search',
  'empty-favor',
  'empty-coupon',
  'empty-history',
  'empty-permission',
  'empty-news',
  'empty-wifi',
  'empty-list',
  'arrow-left-double',
  'arrow-right-double',
  'red-packet',
  'red-packet-fill',
  'order',
  'nav-back-arrow',
  'nav-back',
  'checkbox-mark',
  'arrow-up-fill',
  'arrow-down-fill',
  'backspace',
  'android-circle-fill',
  'android-fill',
  'question',
  'pause',
  'close',
  'volume-up',
  'volume-off',
  'info',
  'error',
  'lock-opened-fill',
  'lock-fill',
  'lock',
  'photo-fill',
  'photo',
  'account-fill',
  'minus-people-fill',
  'plus-people-fill',
  'account',
  'thumb-down-fill',
  'thumb-down',
  'thumb-up-fill',
  'thumb-up',
  'person-delete-fill',
  'cut',
  'fingerprint',
  'home-fill',
  'home',
  'hourglass-half-fill',
  'hourglass',
  'lock-open',
  'integral-fill',
  'integral',
  'coupon',
  'coupon-fill',
  'kefu-ermai',
  'scan',
  'rmb',
  'rmb-circle-fill',
  'rmb-circle',
  'gift',
  'gift-fill',
  'bookmark-fill',
  'zhuanfa',
  'eye-off-outline',
  'eye-off',
  'pause-circle',
  'play-circle',
  'pause-circle-fill',
  'play-circle-fill',
  'grid',
  'play-right',
  'play-left',
  'calendar',
  'rewind-right',
  'rewind-left',
  'skip-forward-right',
  'skip-back-left',
  'play-left-fill',
  'play-right-fill',
  'grid-fill',
  'rewind-left-fill',
  'rewind-right-fill',
  'pushpin',
  'star',
  'star-fill',
  'server-fill',
  'server-man',
  'edit-pen',
  'edit-pen-fill',
  'wifi',
  'wifi-off',
  'file-text',
  'file-text-fill',
  'more-dot-fill',
  'minus',
  'minus-circle',
  'plus',
  'plus-circle',
  'minus-circle-fill',
  'plus-circle-fill',
  'email',
  'email-fill',
  'phone',
  'phone-fill',
  'clock',
  'car',
  'car-fill',
  'warning',
  'warning-fill',
  'search',
  'baidu-circle-fill',
  'baidu',
  'facebook',
  'facebook-circle-fill',
  'qzone',
  'qzone-circle-fill',
  'moments-circel-fill',
  'moments',
  'qq-circle-fill',
  'qq-fill',
  'weibo',
  'weibo-circle-fill',
  'taobao',
  'taobao-circle-fill',
  'twitter',
  'twitter-circle-fill',
  'weixin-circle-fill',
  'weixin-fill',
  'zhifubao-circle-fill',
  'zhifubao',
  'zhihu',
  'zhihu-circle-fill',
  'list',
  'list-dot',
  'setting',
  'bell',
  'bell-fill',
  'attach',
  'shopping-cart',
  'shopping-cart-fill',
  'tags',
  'share',
  'question-circle-fill',
  'question-circle',
  'error-circle',
  'checkmark-circle',
  'close-circle',
  'info-circle',
  'md-person-add',
  'md-person-fill',
  'bag-fill',
  'bag',
  'chat-fill',
  'chat',
  'more-circle',
  'more-circle-fill',
  'volume',
  'volume-fill',
  'reload',
  'camera',
  'heart',
  'heart-fill',
  'minus-square-fill',
  'plus-square-fill',
  'pushpin-fill',
  'camera-fill',
  'setting-fill',
  'google',
  'ie',
  'apple-fill',
  'chrome-circle-fill',
  'github-circle-fill',
  'IE-circle-fill',
  'google-circle-fill',
  'arrow-down',
  'arrow-left',
  'map',
  'man-add-fill',
  'tags-fill',
  'arrow-leftward',
  'arrow-rightward',
  'arrow-downward',
  'arrow-right',
  'arrow-up',
  'arrow-upward',
  'bookmark',
  'eye',
  'man-delete',
  'man-add',
  'trash',
  'error-circle-fill',
  'calendar-fill',
  'checkmark-circle-fill',
  'close-circle-fill',
  'clock-fill',
  'checkmark',
  'download',
  'eye-fill',
  'mic-off',
  'mic',
  'info-circle-fill',
  'map-fill',
  'trash-fill',
  'volume-off-fill',
  'volume-up-fill',
  'share-fill',
] as const

const DINGTALK_H5_ICON_LABELS: Record<string, string> = {
  account: '用户',
  'account-fill': '用户填充',
  attach: '附件',
  bag: '包',
  bell: '通知',
  'bell-fill': '通知填充',
  bookmark: '书签',
  calendar: '日历',
  chat: '消息',
  checkmark: '完成',
  'checkmark-circle': '完成圆形',
  clock: '时间',
  close: '关闭',
  coupon: '券',
  download: '下载',
  'edit-pen': '编辑',
  email: '邮件',
  eye: '查看',
  'file-text': '文件文本',
  fingerprint: '指纹',
  gift: '礼物',
  grid: '宫格',
  'grid-fill': '宫格填充',
  home: '首页',
  'home-fill': '首页填充',
  info: '信息',
  integral: '积分',
  level: '等级',
  list: '列表',
  'list-dot': '点列',
  lock: '锁定',
  'man-add': '添加人员',
  'man-delete': '删除人员',
  map: '地图',
  order: '订单',
  phone: '电话',
  photo: '图片',
  plus: '新增',
  'plus-circle': '新增圆形',
  question: '问题',
  reload: '刷新',
  scan: '扫码',
  search: '搜索',
  setting: '设置',
  'setting-fill': '设置填充',
  share: '分享',
  star: '星标',
  tags: '标签',
  trash: '删除',
  'trash-fill': '删除填充',
  warning: '警告',
}

export const DINGTALK_H5_ICON_ALIASES: Record<string, string> = {
  account: 'account-fill',
  dashboard: 'grid',
  history: 'order',
  hrbp: 'man-add',
  manager: 'account-fill',
  mine: 'file-text',
  org: 'setting',
  performance: 'list',
  summary: 'order',
  template: 'file-text',
}

const DINGTALK_H5_ICON_ALIAS_LABELS: Record<string, string> = {
  account: '用户账号',
  dashboard: '工作台',
  history: '历史绩效',
  hrbp: 'HRBP评价',
  manager: '上级评价',
  mine: '我的绩效',
  org: '流程制定',
  performance: '绩效管理',
  summary: 'HRBP汇总',
  template: '绩效参数',
}

const aliasesByIcon = Object.entries(DINGTALK_H5_ICON_ALIASES).reduce((result, [alias, icon]) => {
  if (!result[icon]) result[icon] = []
  result[icon].push(alias)
  return result
}, {} as Record<string, string[]>)

export const DINGTALK_H5_ICON_OPTIONS: DingTalkH5IconOption[] = DINGTALK_H5_ICON_NAMES.map(value => ({
  value,
  label: DINGTALK_H5_ICON_LABELS[value] || value,
  aliases: aliasesByIcon[value] || [],
}))

export function resolveDingTalkH5IconValue(icon: string) {
  const key = String(icon || '').trim()
  return DINGTALK_H5_ICON_ALIASES[key] || key
}

export function dingtalkH5IconLabel(icon: string) {
  const rawValue = String(icon || '').trim()
  const value = resolveDingTalkH5IconValue(rawValue)
  return DINGTALK_H5_ICON_ALIAS_LABELS[rawValue] || DINGTALK_H5_ICON_LABELS[value] || value || '-'
}
