package admin

type routeMethodPerm struct {
	method string
	path   string
	perm   string
}

var routeMethodPerms = map[string]string{
	"GET /api/v2/admin/home":                    "",
	"DELETE /api/v2/admin/home/recommendations": "home",

	"GET /api/v2/admin/managers":                            "mgr:list",
	"POST /api/v2/admin/managers":                           "mgr:add",
	"DELETE /api/v2/admin/managers":                         "mgr:del",
	"GET /api/v2/admin/admin-sessions":                      "online:list",
	"POST /api/v2/admin/admin-sessions/batch-force-offline": "online:force_offline",
	"POST /api/v2/admin/auth/logout":                        "",
	"GET /api/v2/admin/logs":                                "log:list",
	"DELETE /api/v2/admin/logs":                             "log:del",

	"PUT /api/v2/admin/settings":                             "setup:edit",
	"PUT /api/v2/admin/settings/content":                     "setup:edit",
	"GET /api/v2/admin/settings/mini-qr":                     "setup:edit",
	"GET /api/v2/admin/settings/debug-token":                 "setup:edit",
	"GET /api/v2/admin/dingtalk/settings":                    "dingtalk:settings:list",
	"PUT /api/v2/admin/dingtalk/settings":                    "dingtalk:settings:edit",
	"POST /api/v2/admin/dingtalk/settings/notification-test": "dingtalk:settings:edit",

	"GET /api/v2/admin/dingtalk/user-bindings":             "dingtalk:bindings:list",
	"POST /api/v2/admin/dingtalk/user-bindings":            "dingtalk:bindings:edit",
	"GET /api/v2/admin/dingtalk/perf-reviews":              "dingtalk:perf-reviews:list",
	"DELETE /api/v2/admin/dingtalk/perf-reviews":           "dingtalk:perf-reviews:del",
	"GET /api/v2/admin/dingtalk/perf-histories":            "dingtalk:perf-histories:list",
	"DELETE /api/v2/admin/dingtalk/perf-histories":         "dingtalk:perf-histories:del",
	"GET /api/v2/admin/users":                              "user:list",
	"POST /api/v2/admin/users":                             "user:add",
	"DELETE /api/v2/admin/users":                           "user:del",
	"GET /api/v2/admin/users/form-fields":                  "user:list",
	"PUT /api/v2/admin/users/form-fields":                  "user:edit",
	"GET /api/v2/admin/users/data":                         "user:list",
	"GET /api/v2/admin/users/data/export":                  "user:list",
	"GET /api/v2/admin/user-sessions":                      "online:list",
	"POST /api/v2/admin/user-sessions/batch-force-offline": "online:force_offline",

	"GET /api/v2/admin/news":    "news:list",
	"POST /api/v2/admin/news":   "news:add",
	"DELETE /api/v2/admin/news": "news:del",

	"GET /api/v2/admin/enrollments":    "enroll:list",
	"POST /api/v2/admin/enrollments":   "enroll:add",
	"DELETE /api/v2/admin/enrollments": "enroll:del",

	"GET /api/v2/admin/events":           "event:list",
	"POST /api/v2/admin/events":          "event:add",
	"DELETE /api/v2/admin/events":        "event:del",
	"GET /api/v2/admin/event-dept-users": "event:list",

	"GET /api/v2/admin/dict/types":  "dict:list",
	"GET /api/v2/admin/dict/items":  "",
	"POST /api/v2/admin/dict/items": "dict:add",

	"GET /api/v2/admin/departments/tree": "dept:list",
	"POST /api/v2/admin/departments":     "dept:add",
	"GET /api/v2/admin/positions":        "user:list,position:list",
	"POST /api/v2/admin/positions":       "position:add",

	"GET /api/v2/admin/roles/application-permissions": "role:list",
	"GET /api/v2/admin/roles":                         "role:list",
	"POST /api/v2/admin/roles":                        "role:add",
	"DELETE /api/v2/admin/roles":                      "role:del",

	"GET /api/v2/admin/permissions/tree": "menu:list",
	"GET /api/v2/admin/permissions":      "menu:list",
	"POST /api/v2/admin/permissions":     "menu:add",
	"GET /api/v2/admin/me/menus":         "",
	"GET /api/v2/admin/me/perms":         "",
	"PATCH /api/v2/admin/me/password":    "mgr:edit",

	"GET /api/v2/admin/survey-types":                      "survey:list",
	"POST /api/v2/admin/survey-schema/parse":              "survey:edit",
	"POST /api/v2/admin/survey-expressions/evaluate":      "survey:edit",
	"GET /api/v2/admin/survey-report/enroll":              "survey:list",
	"GET /api/v2/admin/survey-report/enroll/export":       "response:export",
	"GET /api/v2/admin/survey-report/event":               "survey:list",
	"GET /api/v2/admin/survey-report/event/export":        "response:export",
	"GET /api/v2/admin/survey-report/survey":              "survey:list",
	"GET /api/v2/admin/survey-report/survey/export":       "response:export",
	"GET /api/v2/admin/surveys":                           "survey:list",
	"POST /api/v2/admin/surveys":                          "survey:add",
	"DELETE /api/v2/admin/survey-responses":               "response:del",
	"POST /api/v2/admin/survey-resources":                 "survey:edit",
	"GET /api/v2/admin/survey-question-bank":              "question-bank:list",
	"POST /api/v2/admin/survey-question-bank":             "question-bank:add",
	"GET /api/v2/admin/survey-question-bank/categories":   "question-bank:list",
	"GET /api/v2/admin/survey-notifications":              "survey:list",
	"GET /api/v2/admin/survey-notifications/unread-count": "survey:list",
	"GET /api/v2/admin/survey-template-presets":           "survey:list,survey:edit",
	"PUT /api/v2/admin/survey-template-presets":           "survey:list,survey:edit",

	"GET /api/v2/admin/exams":                         "exam:list",
	"POST /api/v2/admin/exams":                        "exam:add,exam:edit",
	"POST /api/v2/admin/exam-resources":               "exam:edit",
	"GET /api/v2/admin/exam-question-bank":            "question-bank:list",
	"POST /api/v2/admin/exam-question-bank":           "question-bank:add",
	"GET /api/v2/admin/exam-question-bank/categories": "question-bank:list",
}

var routeMethodPermPatterns = []routeMethodPerm{
	{method: "GET", path: "/api/v2/admin/managers/:id", perm: "mgr:list"},
	{method: "PUT", path: "/api/v2/admin/managers/:id", perm: "mgr:edit"},
	{method: "DELETE", path: "/api/v2/admin/managers/:id", perm: "mgr:del"},
	{method: "PATCH", path: "/api/v2/admin/managers/:id/status", perm: "mgr:edit"},
	{method: "PATCH", path: "/api/v2/admin/managers/:id/password", perm: "mgr:edit"},
	{method: "POST", path: "/api/v2/admin/admin-sessions/:id/force-offline", perm: "online:force_offline"},
	{method: "PATCH", path: "/api/v2/admin/dingtalk/user-bindings/:id/status", perm: "dingtalk:bindings:edit"},
	{method: "DELETE", path: "/api/v2/admin/dingtalk/user-bindings/:id", perm: "dingtalk:bindings:edit"},
	{method: "GET", path: "/api/v2/admin/dingtalk/perf-reviews/:id", perm: "dingtalk:perf-reviews:detail"},
	{method: "DELETE", path: "/api/v2/admin/dingtalk/perf-reviews/:id", perm: "dingtalk:perf-reviews:del"},
	{method: "DELETE", path: "/api/v2/admin/dingtalk/perf-histories/:id", perm: "dingtalk:perf-histories:del"},

	{method: "GET", path: "/api/v2/admin/users/:id", perm: "user:list"},
	{method: "GET", path: "/api/v2/admin/users/by-openid/:openid", perm: "user:list"},
	{method: "PUT", path: "/api/v2/admin/users/:id", perm: "user:edit"},
	{method: "DELETE", path: "/api/v2/admin/users/:id", perm: "user:del"},
	{method: "PATCH", path: "/api/v2/admin/users/:id/status", perm: "user:edit"},
	{method: "PATCH", path: "/api/v2/admin/users/:id/password", perm: "user:edit"},
	{method: "DELETE", path: "/api/v2/admin/users/data/:id", perm: "user:del"},
	{method: "POST", path: "/api/v2/admin/user-sessions/:id/force-offline", perm: "online:force_offline"},

	{method: "GET", path: "/api/v2/admin/news/:id", perm: "news:list"},
	{method: "PUT", path: "/api/v2/admin/news/:id", perm: "news:edit"},
	{method: "DELETE", path: "/api/v2/admin/news/:id", perm: "news:del"},
	{method: "PATCH", path: "/api/v2/admin/news/:id/status", perm: "news:edit"},
	{method: "PATCH", path: "/api/v2/admin/news/:id/recommendation", perm: "news:edit"},
	{method: "PATCH", path: "/api/v2/admin/news/:id/sort", perm: "news:edit"},
	{method: "PATCH", path: "/api/v2/admin/news/:id/forms", perm: "news:edit"},
	{method: "PATCH", path: "/api/v2/admin/news/:id/picture", perm: "news:edit"},
	{method: "PATCH", path: "/api/v2/admin/news/:id/content", perm: "news:edit"},

	{method: "GET", path: "/api/v2/admin/enrollments/:id", perm: "enroll:list"},
	{method: "PUT", path: "/api/v2/admin/enrollments/:id", perm: "enroll:edit"},
	{method: "DELETE", path: "/api/v2/admin/enrollments/:id", perm: "enroll:del"},
	{method: "PATCH", path: "/api/v2/admin/enrollments/:id/status", perm: "enroll:edit"},
	{method: "PATCH", path: "/api/v2/admin/enrollments/:id/sort", perm: "enroll:edit"},
	{method: "PATCH", path: "/api/v2/admin/enrollments/:id/recommendation", perm: "enroll:edit"},
	{method: "PATCH", path: "/api/v2/admin/enrollments/:id/forms", perm: "enroll:edit"},
	{method: "POST", path: "/api/v2/admin/enrollments/:id/clear", perm: "enroll:del"},
	{method: "GET", path: "/api/v2/admin/enrollments/:id/joins", perm: "enroll:list"},
	{method: "DELETE", path: "/api/v2/admin/enrollments/:id/joins/:joinId", perm: "enroll:del"},
	{method: "DELETE", path: "/api/v2/admin/enrollments/:id/joins", perm: "enroll:del"},
	{method: "GET", path: "/api/v2/admin/enrollments/:id/users", perm: "enroll:list"},
	{method: "GET", path: "/api/v2/admin/enrollments/:id/stats", perm: "enroll:list"},
	{method: "DELETE", path: "/api/v2/admin/enrollments/:id/users/:userId", perm: "enroll:del"},
	{method: "DELETE", path: "/api/v2/admin/enrollments/:id/users", perm: "enroll:del"},
	{method: "PUT", path: "/api/v2/admin/enrollments/:id/users/:userId/forms", perm: "enroll:edit"},
	{method: "GET", path: "/api/v2/admin/enrollments/:id/export", perm: "enroll:list"},
	{method: "POST", path: "/api/v2/admin/enrollments/:id/export", perm: "enroll:list"},
	{method: "DELETE", path: "/api/v2/admin/enrollments/:id/export", perm: "enroll:del"},

	{method: "GET", path: "/api/v2/admin/events/:id", perm: "event:list"},
	{method: "PUT", path: "/api/v2/admin/events/:id", perm: "event:edit"},
	{method: "DELETE", path: "/api/v2/admin/events/:id", perm: "event:del"},
	{method: "PATCH", path: "/api/v2/admin/events/:id/status", perm: "event:edit"},
	{method: "PATCH", path: "/api/v2/admin/events/:id/recommendation", perm: "event:edit"},
	{method: "PATCH", path: "/api/v2/admin/events/:id/top", perm: "event:edit"},
	{method: "GET", path: "/api/v2/admin/events/:id/participants", perm: "event:list"},
	{method: "PUT", path: "/api/v2/admin/events/:id/participants/:participantId", perm: "event:edit"},
	{method: "DELETE", path: "/api/v2/admin/events/:id/participants/:participantId", perm: "event:del"},
	{method: "DELETE", path: "/api/v2/admin/events/:id/participants", perm: "event:del"},
	{method: "GET", path: "/api/v2/admin/events/:id/dynamics", perm: "event:list"},
	{method: "POST", path: "/api/v2/admin/events/:id/dynamics", perm: "event:add"},
	{method: "PUT", path: "/api/v2/admin/events/:id/dynamics/:dynamicId", perm: "event:edit"},
	{method: "DELETE", path: "/api/v2/admin/events/:id/dynamics/:dynamicId", perm: "event:del"},
	{method: "DELETE", path: "/api/v2/admin/events/:id/dynamics", perm: "event:del"},
	{method: "GET", path: "/api/v2/admin/events/:id/scores", perm: "event:list"},
	{method: "POST", path: "/api/v2/admin/events/:id/scores", perm: "event:edit"},
	{method: "PUT", path: "/api/v2/admin/events/:id/scores/:scoreId", perm: "event:edit"},

	{method: "PUT", path: "/api/v2/admin/dict/items/:id", perm: "dict:edit"},
	{method: "DELETE", path: "/api/v2/admin/dict/items/:id", perm: "dict:del"},
	{method: "DELETE", path: "/api/v2/admin/dict/types/:typeCode/items", perm: "dict:del"},
	{method: "PATCH", path: "/api/v2/admin/dict/types/:typeCode", perm: "dict:edit"},
	{method: "PUT", path: "/api/v2/admin/departments/:id", perm: "dept:edit"},
	{method: "DELETE", path: "/api/v2/admin/departments/:id", perm: "dept:del"},
	{method: "PUT", path: "/api/v2/admin/positions/:id", perm: "position:edit"},
	{method: "DELETE", path: "/api/v2/admin/positions/:id", perm: "position:del"},
	{method: "PUT", path: "/api/v2/admin/roles/:id", perm: "role:edit"},
	{method: "DELETE", path: "/api/v2/admin/roles/:id", perm: "role:del"},
	{method: "PUT", path: "/api/v2/admin/permissions/:key", perm: "menu:edit"},
	{method: "DELETE", path: "/api/v2/admin/permissions/:key", perm: "menu:del"},

	{method: "GET", path: "/api/v2/admin/surveys/:id", perm: "survey:list"},
	{method: "PUT", path: "/api/v2/admin/surveys/:id", perm: "survey:edit"},
	{method: "DELETE", path: "/api/v2/admin/surveys/:id", perm: "survey:del"},
	{method: "PATCH", path: "/api/v2/admin/surveys/:id/status", perm: "survey:status"},
	{method: "POST", path: "/api/v2/admin/surveys/:id/copy", perm: "survey:copy"},
	{method: "GET", path: "/api/v2/admin/surveys/:id/statistics", perm: "survey:list"},
	{method: "GET", path: "/api/v2/admin/surveys/:id/responses", perm: "response:list"},
	{method: "GET", path: "/api/v2/admin/surveys/:id/responses/export", perm: "response:export"},
	{method: "GET", path: "/api/v2/admin/survey-responses/:id", perm: "response:list"},
	{method: "DELETE", path: "/api/v2/admin/survey-responses/:id", perm: "response:del"},
	{method: "GET", path: "/api/v2/admin/surveys/:id/channels", perm: "survey:list"},
	{method: "POST", path: "/api/v2/admin/surveys/:id/channels", perm: "survey:edit"},
	{method: "DELETE", path: "/api/v2/admin/survey-channels/:id", perm: "survey:edit"},
	{method: "GET", path: "/api/v2/admin/surveys/:id/resources", perm: "survey:list"},
	{method: "DELETE", path: "/api/v2/admin/survey-resources/:id", perm: "survey:edit"},
	{method: "PUT", path: "/api/v2/admin/survey-question-bank/:id", perm: "question-bank:edit"},
	{method: "DELETE", path: "/api/v2/admin/survey-question-bank/:id", perm: "question-bank:del"},
	{method: "PATCH", path: "/api/v2/admin/survey-notifications/:id/read", perm: "survey:list"},

	{method: "GET", path: "/api/v2/admin/exams/:id", perm: "exam:list"},
	{method: "PUT", path: "/api/v2/admin/exams/:id", perm: "exam:edit"},
	{method: "DELETE", path: "/api/v2/admin/exams/:id", perm: "exam:del"},
	{method: "PATCH", path: "/api/v2/admin/exams/:id/status", perm: "exam:edit"},
	{method: "GET", path: "/api/v2/admin/exams/:id/records", perm: "exam:list"},
	{method: "GET", path: "/api/v2/admin/exams/:id/records/:recordId", perm: "exam:list"},
	{method: "DELETE", path: "/api/v2/admin/exams/:id/records/:recordId", perm: "exam:del"},
	{method: "DELETE", path: "/api/v2/admin/exams/:id/records", perm: "exam:del"},
	{method: "GET", path: "/api/v2/admin/exams/:id/statistics", perm: "exam:list"},
	{method: "GET", path: "/api/v2/admin/exams/:id/resources", perm: "exam:list"},
	{method: "DELETE", path: "/api/v2/admin/exam-resources/:id", perm: "exam:edit"},
	{method: "PUT", path: "/api/v2/admin/exam-question-bank/:id", perm: "question-bank:edit"},
	{method: "DELETE", path: "/api/v2/admin/exam-question-bank/:id", perm: "question-bank:del"},
}
