package admin

type routeMethodPerm struct {
	method string
	path   string
	perm   string
}

var routeMethodPerms = map[string]string{
	"GET /api/v2/admin/home":                    "",
	"DELETE /api/v2/admin/home/recommendations": "home",

	"GET /api/v2/admin/managers":                            "mgr:list",
	"POST /api/v2/admin/managers":                           "mgr:add",
	"DELETE /api/v2/admin/managers":                         "mgr:del",
	"GET /api/v2/admin/admin-sessions":                      "online:list",
	"POST /api/v2/admin/admin-sessions/batch-force-offline": "online:force_offline",
	"POST /api/v2/admin/auth/logout":                        "",
	"GET /api/v2/admin/logs":                                "log:list",
	"DELETE /api/v2/admin/logs":                             "log:del",

	"PUT /api/v2/admin/settings":                             "setup:edit",
	"GET /api/v2/admin/settings/content":                     "setup:list",
	"PUT /api/v2/admin/settings/content":                     "setup:edit",
	"GET /api/v2/admin/settings/mini-qr":                     "setup:edit",
	"GET /api/v2/admin/settings/debug-token":                 "setup:edit",
	"GET /api/v2/admin/dingtalk/settings":                    "dingtalk:settings:list",
	"POST /api/v2/admin/uploads":                             "upload:create",
	"PUT /api/v2/admin/dingtalk/settings":                    "dingtalk:settings:edit",
	"POST /api/v2/admin/dingtalk/settings/notification-test": "dingtalk:settings:edit",

	"GET /api/v2/admin/dingtalk/user-bindings":             "dingtalk:bindings:list",
	"POST /api/v2/admin/dingtalk/user-bindings":            "dingtalk:bindings:edit",
	"GET /api/v2/admin/dingtalk/perf-reviews":              "dingtalk:perf-reviews:list",
	"DELETE /api/v2/admin/dingtalk/perf-reviews":           "dingtalk:perf-reviews:del",
	"GET /api/v2/admin/dingtalk/perf-histories":            "dingtalk:perf-histories:list",
	"DELETE /api/v2/admin/dingtalk/perf-histories":         "dingtalk:perf-histories:del",
	"GET /api/v2/admin/users":                              "user:list",
	"POST /api/v2/admin/users":                             "user:add",
	"DELETE /api/v2/admin/users":                           "user:del",
	"GET /api/v2/admin/users/form-fields":                  "user:list",
	"PUT /api/v2/admin/users/form-fields":                  "user:edit",
	"GET /api/v2/admin/users/data":                         "user:list",
	"GET /api/v2/admin/users/data/export":                  "user:list",
	"GET /api/v2/admin/user-sessions":                      "online:list",
	"POST /api/v2/admin/user-sessions/batch-force-offline": "online:force_offline",

	"GET /api/v2/admin/news":    "news:list",
	"POST /api/v2/admin/news":   "news:add",
	"DELETE /api/v2/admin/news": "news:del",

	"GET /api/v2/admin/enrollments":    "enroll:list",
	"POST /api/v2/admin/enrollments":   "enroll:add",
	"DELETE /api/v2/admin/enrollments": "enroll:del",

	"GET /api/v2/admin/events":           "event:list",
	"POST /api/v2/admin/events":          "event:add",
	"DELETE /api/v2/admin/events":        "event:del",
	"GET /api/v2/admin/event-dept-users": "event:list",

	"GET /api/v2/admin/dict/types":  "dict:list",
	"POST /api/v2/admin/dict/types": "dict:add",
	"GET /api/v2/admin/dict/items":  "dict:list",
	"POST /api/v2/admin/dict/items": "dict:add",

	"GET /api/v2/admin/departments/tree": "dept:list",
	"POST /api/v2/admin/departments":     "dept:add",
	"GET /api/v2/admin/positions":        "user:list,position:list",
	"POST /api/v2/admin/positions":       "position:add",

	"GET /api/v2/admin/roles/application-permissions": "role:list",
	"GET /api/v2/admin/roles":                         "role:list",
	"POST /api/v2/admin/roles":                        "role:add",
	"DELETE /api/v2/admin/roles":                      "role:del",

	"GET /api/v2/admin/permissions/tree": "menu:list",
	"GET /api/v2/admin/permissions":      "menu:list",
	"POST /api/v2/admin/permissions":     "menu:add",
	"GET /api/v2/admin/me/menus":         "",
	"GET /api/v2/admin/me/perms":         "",
	"PATCH /api/v2/admin/me/password":    "mgr:edit",

	"GET /api/v2/admin/survey-types":                      "survey:list",
	"POST /api/v2/admin/survey-schema/parse":              "survey:edit",
	"POST /api/v2/admin/survey-expressions/evaluate":      "survey:edit",
	"GET /api/v2/admin/survey-report/enroll":              "survey:list",
	"GET /api/v2/admin/survey-report/enroll/export":       "response:export",
	"GET /api/v2/admin/survey-report/event":               "survey:list",
	"GET /api/v2/admin/survey-report/event/export":        "response:export",
	"GET /api/v2/admin/survey-report/survey":              "survey:list",
	"GET /api/v2/admin/survey-report/survey/export":       "response:export",
	"GET /api/v2/admin/surveys":                           "survey:list",
	"POST /api/v2/admin/surveys":                          "survey:add",
	"DELETE /api/v2/admin/survey-responses":               "response:del",
	"POST /api/v2/admin/survey-resources":                 "survey:edit",
	"GET /api/v2/admin/survey-question-bank":              "question-bank:list",
	"POST /api/v2/admin/survey-question-bank":             "question-bank:add",
	"GET /api/v2/admin/survey-question-bank/categories":   "question-bank:list",
	"GET /api/v2/admin/survey-notifications":              "survey:list",
	"GET /api/v2/admin/survey-notifications/unread-count": "survey:list",
	"GET /api/v2/admin/survey-template-presets":           "survey:list,survey:edit",
	"PUT /api/v2/admin/survey-template-presets":           "survey:list,survey:edit",

	"GET /api/v2/admin/exams":                         "exam:list",
	"POST /api/v2/admin/exams":                        "exam:add,exam:edit",
	"POST /api/v2/admin/exam-resources":               "exam:edit",
	"GET /api/v2/admin/exam-question-bank":            "question-bank:list",
	"POST /api/v2/admin/exam-question-bank":           "question-bank:add",
	"GET /api/v2/admin/exam-question-bank/categories": "question-bank:list",

	"GET /api/v2/admin/workflow-definitions":                     "workflow:list",
	"POST /api/v2/admin/workflow-definitions":                    "workflow:add",
	"GET /api/v2/admin/workflow-org-approver-identities":         "workflow:org-approver:list",
	"GET /api/v2/admin/workflow-org-approver-assignments":        "workflow:org-approver:list",
	"PUT /api/v2/admin/workflow-org-approver-assignments":        "workflow:org-approver:edit",
	"GET /api/v2/admin/workflow-published-definitions":           "workflow:instance:start",
	"GET /api/v2/admin/workflow-user-options":                    "workflow:instance:start",
	"GET /api/v2/admin/workflow-department-options":              "workflow:instance:start",
	"GET /api/v2/admin/workflow-instances":                       "workflow:instance:list",
	"POST /api/v2/admin/workflow-instances":                      "workflow:instance:start",
	"DELETE /api/v2/admin/workflow-instances":                    "workflow:instance:delete",
	"GET /api/v2/admin/workflow-tasks":                           "workflow:task:list",
	"GET /api/v2/admin/workflow-notifications":                   "workflow:notification:list",
	"POST /api/v2/admin/workflow-notifications/dispatch-due":     "workflow:notification:retry",
	"GET /api/v2/admin/in-app-notifications":                     "notification:list",
	"GET /api/v2/admin/in-app-notifications/unread-count":        "notification:list",
	"GET /api/v2/admin/in-app-notifications/recipient-options":   "notification:send",
	"PATCH /api/v2/admin/in-app-notifications/read-all":          "notification:read",
	"POST /api/v2/admin/in-app-notifications":                    "notification:send",
	"GET /api/v2/admin/dingtalk-notifications/recipient-options": "notification:dingtalk:send",
	"POST /api/v2/admin/dingtalk-notifications":                  "notification:dingtalk:send",

	"GET /api/v2/admin/scheduled-tasks":               "scheduled-task:list",
	"POST /api/v2/admin/scheduled-tasks":              "scheduled-task:add",
	"POST /api/v2/admin/scheduled-tasks/cron-preview": "scheduled-task:list",
	"GET /api/v2/admin/scheduled-task-handlers":       "scheduled-task:list",
	"GET /api/v2/admin/scheduled-task-runs":           "scheduled-task:run:list",
	"GET /api/v2/admin/scheduled-task-workers":        "scheduled-task:worker:list",
}

var routeMethodPermPatterns = []routeMethodPerm{
	{method: "GET", path: "/api/v2/admin/managers/:id", perm: "mgr:list"},
	{method: "PUT", path: "/api/v2/admin/managers/:id", perm: "mgr:edit"},
	{method: "DELETE", path: "/api/v2/admin/managers/:id", perm: "mgr:del"},
	{method: "PATCH", path: "/api/v2/admin/managers/:id/status", perm: "mgr:edit"},
	{method: "PATCH", path: "/api/v2/admin/managers/:id/password", perm: "mgr:edit"},
	{method: "POST", path: "/api/v2/admin/admin-sessions/:id/force-offline", perm: "online:force_offline"},
	{method: "PATCH", path: "/api/v2/admin/dingtalk/user-bindings/:id/status", perm: "dingtalk:bindings:edit"},
	{method: "DELETE", path: "/api/v2/admin/dingtalk/user-bindings/:id", perm: "dingtalk:bindings:edit"},
	{method: "GET", path: "/api/v2/admin/dingtalk/perf-reviews/:id", perm: "dingtalk:perf-reviews:detail"},
	{method: "DELETE", path: "/api/v2/admin/dingtalk/perf-reviews/:id", perm: "dingtalk:perf-reviews:del"},
	{method: "DELETE", path: "/api/v2/admin/dingtalk/perf-histories/:id", perm: "dingtalk:perf-histories:del"},

	{method: "GET", path: "/api/v2/admin/users/:id", perm: "user:list"},
	{method: "GET", path: "/api/v2/admin/users/by-openid/:openid", perm: "user:list"},
	{method: "PUT", path: "/api/v2/admin/users/:id", perm: "user:edit"},
	{method: "DELETE", path: "/api/v2/admin/users/:id", perm: "user:del"},
	{method: "PATCH", path: "/api/v2/admin/users/:id/status", perm: "user:edit"},
	{method: "PATCH", path: "/api/v2/admin/users/:id/password", perm: "user:edit"},
	{method: "DELETE", path: "/api/v2/admin/users/data/:id", perm: "user:del"},
	{method: "POST", path: "/api/v2/admin/user-sessions/:id/force-offline", perm: "online:force_offline"},

	{method: "GET", path: "/api/v2/admin/news/:id", perm: "news:list"},
	{method: "PUT", path: "/api/v2/admin/news/:id", perm: "news:edit"},
	{method: "DELETE", path: "/api/v2/admin/news/:id", perm: "news:del"},
	{method: "PATCH", path: "/api/v2/admin/news/:id/status", perm: "news:status"},
	{method: "PATCH", path: "/api/v2/admin/news/:id/recommendation", perm: "news:vouch"},
	{method: "PATCH", path: "/api/v2/admin/news/:id/sort", perm: "news:edit"},
	{method: "PATCH", path: "/api/v2/admin/news/:id/forms", perm: "news:edit"},
	{method: "PATCH", path: "/api/v2/admin/news/:id/picture", perm: "news:edit"},
	{method: "PATCH", path: "/api/v2/admin/news/:id/content", perm: "news:edit"},

	{method: "GET", path: "/api/v2/admin/enrollments/:id", perm: "enroll:list"},
	{method: "PUT", path: "/api/v2/admin/enrollments/:id", perm: "enroll:edit"},
	{method: "DELETE", path: "/api/v2/admin/enrollments/:id", perm: "enroll:del"},
	{method: "PATCH", path: "/api/v2/admin/enrollments/:id/status", perm: "enroll:status"},
	{method: "PATCH", path: "/api/v2/admin/enrollments/:id/sort", perm: "enroll:edit"},
	{method: "PATCH", path: "/api/v2/admin/enrollments/:id/recommendation", perm: "enroll:vouch"},
	{method: "PATCH", path: "/api/v2/admin/enrollments/:id/forms", perm: "enroll:edit"},
	{method: "POST", path: "/api/v2/admin/enrollments/:id/clear", perm: "enroll:del"},
	{method: "GET", path: "/api/v2/admin/enrollments/:id/joins", perm: "enroll:list"},
	{method: "DELETE", path: "/api/v2/admin/enrollments/:id/joins/:joinId", perm: "enroll:del"},
	{method: "DELETE", path: "/api/v2/admin/enrollments/:id/joins", perm: "enroll:del"},
	{method: "GET", path: "/api/v2/admin/enrollments/:id/users", perm: "enroll:users"},
	{method: "GET", path: "/api/v2/admin/enrollments/:id/stats", perm: "enroll:list"},
	{method: "DELETE", path: "/api/v2/admin/enrollments/:id/users/:userId", perm: "enroll:del"},
	{method: "DELETE", path: "/api/v2/admin/enrollments/:id/users", perm: "enroll:del"},
	{method: "PUT", path: "/api/v2/admin/enrollments/:id/users/:userId/forms", perm: "enroll:edit"},
	{method: "GET", path: "/api/v2/admin/enrollments/:id/export", perm: "enroll:export"},
	{method: "POST", path: "/api/v2/admin/enrollments/:id/export", perm: "enroll:export"},
	{method: "DELETE", path: "/api/v2/admin/enrollments/:id/export", perm: "enroll:del"},

	{method: "GET", path: "/api/v2/admin/events/:id", perm: "event:list"},
	{method: "PUT", path: "/api/v2/admin/events/:id", perm: "event:edit"},
	{method: "DELETE", path: "/api/v2/admin/events/:id", perm: "event:del"},
	{method: "PATCH", path: "/api/v2/admin/events/:id/status", perm: "event:status"},
	{method: "PATCH", path: "/api/v2/admin/events/:id/recommendation", perm: "event:vouch"},
	{method: "PATCH", path: "/api/v2/admin/events/:id/top", perm: "event:top"},
	{method: "GET", path: "/api/v2/admin/events/:id/participants", perm: "event:users"},
	{method: "PUT", path: "/api/v2/admin/events/:id/participants/:participantId", perm: "event:edit"},
	{method: "DELETE", path: "/api/v2/admin/events/:id/participants/:participantId", perm: "event:del"},
	{method: "DELETE", path: "/api/v2/admin/events/:id/participants", perm: "event:del"},
	{method: "GET", path: "/api/v2/admin/events/:id/dynamics", perm: "event:list"},
	{method: "POST", path: "/api/v2/admin/events/:id/dynamics", perm: "event:add"},
	{method: "PUT", path: "/api/v2/admin/events/:id/dynamics/:dynamicId", perm: "event:edit"},
	{method: "DELETE", path: "/api/v2/admin/events/:id/dynamics/:dynamicId", perm: "event:del"},
	{method: "DELETE", path: "/api/v2/admin/events/:id/dynamics", perm: "event:del"},
	{method: "GET", path: "/api/v2/admin/events/:id/scores", perm: "event:list"},
	{method: "POST", path: "/api/v2/admin/events/:id/scores", perm: "event:edit"},
	{method: "PUT", path: "/api/v2/admin/events/:id/scores/:scoreId", perm: "event:edit"},

	{method: "PUT", path: "/api/v2/admin/dict/items/:id", perm: "dict:edit"},
	{method: "DELETE", path: "/api/v2/admin/dict/items/:id", perm: "dict:del"},
	{method: "DELETE", path: "/api/v2/admin/dict/types/:typeCode/items", perm: "dict:del"},
	{method: "PUT", path: "/api/v2/admin/dict/types/:typeCode", perm: "dict:edit"},
	{method: "DELETE", path: "/api/v2/admin/dict/types/:typeCode", perm: "dict:del"},
	{method: "PATCH", path: "/api/v2/admin/dict/types/:typeCode", perm: "dict:edit"},
	{method: "PUT", path: "/api/v2/admin/departments/:id", perm: "dept:edit"},
	{method: "DELETE", path: "/api/v2/admin/departments/:id", perm: "dept:del"},
	{method: "PUT", path: "/api/v2/admin/positions/:id", perm: "position:edit"},
	{method: "DELETE", path: "/api/v2/admin/positions/:id", perm: "position:del"},
	{method: "PUT", path: "/api/v2/admin/roles/:id", perm: "role:edit"},
	{method: "DELETE", path: "/api/v2/admin/roles/:id", perm: "role:del"},
	{method: "PUT", path: "/api/v2/admin/permissions/:key", perm: "menu:edit"},
	{method: "DELETE", path: "/api/v2/admin/permissions/:key", perm: "menu:del"},

	{method: "GET", path: "/api/v2/admin/surveys/:id", perm: "survey:list"},
	{method: "PUT", path: "/api/v2/admin/surveys/:id", perm: "survey:edit"},
	{method: "DELETE", path: "/api/v2/admin/surveys/:id", perm: "survey:del"},
	{method: "PATCH", path: "/api/v2/admin/surveys/:id/status", perm: "survey:status"},
	{method: "POST", path: "/api/v2/admin/surveys/:id/copy", perm: "survey:copy"},
	{method: "GET", path: "/api/v2/admin/surveys/:id/statistics", perm: "survey:list"},
	{method: "GET", path: "/api/v2/admin/surveys/:id/responses", perm: "response:list"},
	{method: "GET", path: "/api/v2/admin/surveys/:id/responses/export", perm: "response:export"},
	{method: "GET", path: "/api/v2/admin/survey-responses/:id", perm: "response:list"},
	{method: "DELETE", path: "/api/v2/admin/survey-responses/:id", perm: "response:del"},
	{method: "GET", path: "/api/v2/admin/surveys/:id/channels", perm: "survey:list"},
	{method: "POST", path: "/api/v2/admin/surveys/:id/channels", perm: "survey:edit"},
	{method: "DELETE", path: "/api/v2/admin/survey-channels/:id", perm: "survey:edit"},
	{method: "GET", path: "/api/v2/admin/surveys/:id/resources", perm: "survey:list"},
	{method: "DELETE", path: "/api/v2/admin/survey-resources/:id", perm: "survey:edit"},
	{method: "PUT", path: "/api/v2/admin/survey-question-bank/:id", perm: "question-bank:edit"},
	{method: "DELETE", path: "/api/v2/admin/survey-question-bank/:id", perm: "question-bank:del"},
	{method: "PATCH", path: "/api/v2/admin/survey-notifications/:id/read", perm: "survey:list"},

	{method: "GET", path: "/api/v2/admin/exams/:id", perm: "exam:list"},
	{method: "PUT", path: "/api/v2/admin/exams/:id", perm: "exam:edit"},
	{method: "DELETE", path: "/api/v2/admin/exams/:id", perm: "exam:del"},
	{method: "PATCH", path: "/api/v2/admin/exams/:id/status", perm: "exam:edit"},
	{method: "GET", path: "/api/v2/admin/exams/:id/records", perm: "exam:list"},
	{method: "GET", path: "/api/v2/admin/exams/:id/records/:recordId", perm: "exam:list"},
	{method: "DELETE", path: "/api/v2/admin/exams/:id/records/:recordId", perm: "exam:del"},
	{method: "DELETE", path: "/api/v2/admin/exams/:id/records", perm: "exam:del"},
	{method: "GET", path: "/api/v2/admin/exams/:id/statistics", perm: "exam:list"},
	{method: "GET", path: "/api/v2/admin/exams/:id/resources", perm: "exam:list"},
	{method: "DELETE", path: "/api/v2/admin/exam-resources/:id", perm: "exam:edit"},
	{method: "PUT", path: "/api/v2/admin/exam-question-bank/:id", perm: "question-bank:edit"},
	{method: "DELETE", path: "/api/v2/admin/exam-question-bank/:id", perm: "question-bank:del"},

	{method: "GET", path: "/api/v2/admin/workflow-definitions/:id", perm: "workflow:list"},
	{method: "POST", path: "/api/v2/admin/workflow-definitions/:id/copy", perm: "workflow:add"},
	{method: "PUT", path: "/api/v2/admin/workflow-definitions/:id", perm: "workflow:edit"},
	{method: "DELETE", path: "/api/v2/admin/workflow-definitions/:id", perm: "workflow:del"},
	{method: "POST", path: "/api/v2/admin/workflow-definitions/:id/validate", perm: "workflow:edit"},
	{method: "POST", path: "/api/v2/admin/workflow-definitions/:id/publish", perm: "workflow:publish"},
	{method: "GET", path: "/api/v2/admin/workflow-definitions/:id/versions", perm: "workflow:list"},
	{method: "GET", path: "/api/v2/admin/workflow-definitions/:id/versions/:version/changes", perm: "workflow:list"},
	{method: "DELETE", path: "/api/v2/admin/workflow-definitions/:id/versions/:version", perm: "workflow:del"},
	{method: "POST", path: "/api/v2/admin/workflow-definitions/:id/versions/:version/rollback", perm: "workflow:publish"},
	{method: "GET", path: "/api/v2/admin/workflow-published-definitions/:id", perm: "workflow:instance:start"},
	{method: "GET", path: "/api/v2/admin/workflow-instances/:id", perm: "workflow:instance:detail"},
	{method: "POST", path: "/api/v2/admin/workflow-instances/:id/resume", perm: "workflow:instance:start"},
	{method: "POST", path: "/api/v2/admin/workflow-instances/:id/cancel", perm: "workflow:instance:cancel"},
	{method: "DELETE", path: "/api/v2/admin/workflow-instances/:id", perm: "workflow:instance:delete"},
	{method: "POST", path: "/api/v2/admin/workflow-tasks/:id/complete", perm: "workflow:task:complete"},
	{method: "DELETE", path: "/api/v2/admin/workflow-tasks/:id", perm: "workflow:task:delete"},
	{method: "POST", path: "/api/v2/admin/workflow-notifications/:id/retry", perm: "workflow:notification:retry"},
	{method: "PATCH", path: "/api/v2/admin/in-app-notifications/:id/read", perm: "notification:read"},

	{method: "GET", path: "/api/v2/admin/scheduled-tasks/:id", perm: "scheduled-task:list"},
	{method: "PUT", path: "/api/v2/admin/scheduled-tasks/:id", perm: "scheduled-task:edit"},
	{method: "DELETE", path: "/api/v2/admin/scheduled-tasks/:id", perm: "scheduled-task:delete"},
	{method: "PATCH", path: "/api/v2/admin/scheduled-tasks/:id/status", perm: "scheduled-task:status"},
	{method: "POST", path: "/api/v2/admin/scheduled-tasks/:id/run", perm: "scheduled-task:run"},
	{method: "GET", path: "/api/v2/admin/scheduled-task-runs/:id", perm: "scheduled-task:run:list"},
	{method: "POST", path: "/api/v2/admin/scheduled-task-runs/:id/retry", perm: "scheduled-task:run:retry"},
	{method: "POST", path: "/api/v2/admin/scheduled-task-runs/:id/cancel", perm: "scheduled-task:run:cancel"},
}
